version: "3"
services:
  sonos:
    image: chrisns/sonos-aws-iot:${DRONE_BUILD_NUMBER:-latest}
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.40'
          memory: 192M
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_IOT_ENDPOINT_HOST=${AWS_IOT_ENDPOINT_HOST}
      - MQTT_PREFIX=sonos/

networks:
  outside:
    external:
      name: "host"